import {Typography} from '@mui/material';

export default function Noticias(){
    return(
        <div >
            <Typography variant="h4" gutterBottom>Noticias</Typography>
            <Typography>Bienvenido a la sección de noticias</Typography>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis perferendis distinctio accusamus cumque earum molestiae harum et possimus? Voluptatem error pariatur ipsum quasi perferendis porro dolore, repellat suscipit. Dicta provident quos facere sed! Earum sint repellendus sit distinctio nemo non beatae, dolor labore voluptates quisquam, porro illum velit, explicabo iste.</p>
        </div>
    );
}